build:
	clang++ -std=c++20 -g promise.cxx -o promise
	clang++ -std=c++20 -g packaged_task.cxx -o packaged_task

clean:
	rm -rf promise promise.dSYM packaged_task packaged_task.dSYM

run:
	./promise
	./packaged_task
