glog-direct:
	GLOG_stderrthreshold=0 GLOG_logtostderr=1 ./build/src/direct/glog-direct

glog-indirect:
	GLOG_stderrthreshold=0 GLOG_logtostderr=1 ./build/src/indirect/glog-indirect

gflags-direct:
	./build/src/gflags-direct/gflags-direct --verbose  --message hello-gflags